### ISSUE TITLE
3.0.0 support?

### ISSUE THREAD

**Issue by BootsSiR** [domibarton/docker-sabnzbd#38]
v3.0.0 is out

I believe it will require python to be upgraded to 3.5+ in order for this image to work

**Comment by Archcry** [comment]
I saw the notification pop-up today, I tried the easy fix by updating the version to 3.0.2 but as you expected it's incompatible with version 2 of python. I accidentally committed to master because now that I have write access it doesn't create a pull-request by default anymore. Anyways, I will dive into this and try to get it working with python3 (which should be possible).

If you can make a working version in the mean time I would be more than happy to accept your PR.

**Comment by Archcry** [comment]
This issues should be solved with https://github.com/domibarton/docker-sabnzbd/pull/41
